### PR TITLE
Support for file attachments

### PR DESCRIPTION
**Pull request by mackoj**
Add support for file attachments

### CODE REVIEW

**Comment by mackoj** [comment]
Fix for #12

**Comment by godrei** [comment]
Looks greate @mackoj ,
will be available in the steplib soon.

**Comment by mackoj** [comment]
When do you think mailgun will be updated ?

**Comment by godrei** [comment]
Hi @mackoj ,
we solved the step's other issues/user requests, the development was done on friday, it is under testing. I hope tomorrow we will release a new version.

**Pull request merged**
